### ISSUE TITLE
Reminder to add support to Avalonian Culture Shock

### ISSUE THREAD

**Issue by Starblast16** [Kherae/FU-Avali-Triage-Patch#5]
Here's that reminder you asked for.

**Comment by Kherae** [comment]
right, and now the next part: I need you to explain what actually needs support in the mod, because I don't have any inclination to play with the mod installed.

**Comment by Starblast16** [comment]
It adds a bunch of recipes for food that still use the non FU Avali Crops.

**Comment by Kherae** [comment]
'a bunch'...unless I missed 'em it's just two, classicavalon and kiriavalon. mind doublechecking for me?

**Comment by Kherae** [comment]
https://github.com/Kherae/FU-Avali-Triage-Patch/commit/d968438660a24831ac549e7c5ec075291bcde8c3
what I got so far.

**Comment by Starblast16** [comment]
Yeah, I think it was mostly getting it to use the FU version of the Avali Crops. Though I could be thinking of a different Avali related mod. It sometimes gets hard keeping track of what's in what mod.

**Comment by Kherae** [comment]
and done, it's now on steam.

**Comment by Starblast16** [comment]
Thank you very much!
